# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anatolii Pedchenko
title: DevOps Engineer
email: anatolek@ukr.net
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: anatolek
stackoverflow_username: "17447957"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: anatolek
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Credly
  icon: fas fa-certificate
  url: https://www.credly.com/users/anatolii-pedchenko

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Have 7+ years of hands-on experience in DevOps, with a strong emphasis on automation, infrastructure as code, and CI/CD pipelines.
  My detail-oriented and methodical approach to problem-solving allows me to consistently deliver high-quality results.
  By thorough analysis, I execute tasks carefully considering short- and long-term perspectives. 
  With a proven ability to lead and manage small technical teams, I am focused on ensuring project alignment and timely delivery.
  Being patient and ready to share my knowledge, I lead mentorship initiatives for my colleagues to enhance the team expertise and overall project results.

content:
  - title: Skills
    layout: text
    content: |
      - **Cloud:** AWS (VPC, EC2, S3, RDS, EKS, ECS, MSK, IAM, Route53, CloudWatch, ElastiCache, CloudTrail, etc.)
      - **Infrastructure:** HashiCorp Terraform, HashiCorp Vault, HashiCorp Packer
      - **Containerization & Orchestration:** Kubernetes, Helm, Docker, Rancher
      - **Scripting & Programming:** Python, Bash
      - **Configuration Management:** Red Hat Ansible, Ansible Molecule
      - **CI/CD & DevOps:** Jenkins, Git (GitLab/GitHub), JFrog Artifactory, Liquibase
      - **Databases & Data Platforms:** MariaDB, PostgreSQL, Snowflake, Redis, Apache Kafka
      - **Monitoring & Logging:** Logic Monitor, SumoLogic, ELK Stack
      - **Project Management & Collaboration:** Jira, Confluence, Agile (Scrum, Kanban)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: GoTransverse Billing Platform
        link: gotransverse.com
        # link_text: boringcompany.com
        sub_title: DevOps Engineer
        caption: 2018 - 2026
        quote: >
          Project aimed to replace a legacy billing system with a modern, agile solution capable of supporting complex, usage-based pricing models and global currencies
        description: | # this will include new lines to allow paragraphs
            **Responsibilities:**
            - Leading, mentoring, and guiding the DevOps team while aligning infrastructure and automation strategy.
            - Collaborating closely with development, implementation, and security teams to ensure seamless integration and operation.
            - Architecting and managing automated pipelines (CI/CD) and Infrastructure as Code (IaC) for all applications and services.
            - Handling complex incidents.

            **Tools & Technologies:** *Kubernetes, Terraform, Ansible, MariaDB, PostgreSQL, Kafka, Jenkins, GitLab, Artifactory, Logic Monitor, Sumologic*
      - layout: left
        title: Scientific Research Center
        link: kpi.ua/web_rst
        # link_text: boringcompany.com
        sub_title: Research Associate
        caption: 2013 - 2018
        quote: >
          Computer modeling of complex systems and problems of continuum mechanics
        description: | # this will include new lines to allow paragraphs
            **Responsibilities:**
            - Designing and execution of natural experiments to gather data sets.
            - Processing and analyzing experimental data to derive actionable insights and ensure practical applications.
            - Simulation of computer models utilizing finite volume or element methods to handle complex data.
            - Authoring articles and monographs to disseminate findings and contribute to scientific literature.


            **Tools & Technologies:** *OpenFOAM, ANSYS, MathCAD*

  - title: Education
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NTUU "Kyiv Politechnic Institute"
        link: kpi.ua
        caption: 2013 - 2017
        sub_title: Candidate of Engineering Sciences
        quote: >
          Process and Equipment Chemical Technology
        description: | # this will include new lines to allow paragraphs
          Defended scientific dissertation on the topic *"Thermoelectric State of Castner Graphitization Furnaces"*.

          The dissertation deals with the important scientific task of creating the scientific basis for development and enhancement of furnace equipment and its operation instructions during the graphitization process of large-size electrode production in Castner`s furnace.

  - title: Certifications
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: "CKS: Certified Kubernetes Security Specialist"
        link: https://www.credly.com/badges/b4098cc6-7840-4461-bcd6-59308edf2b85
        link_text: credly link
        caption: February 14, 2026 – February 15, 2028
        description: |
          <img src="images/CKS.png" alt="Certified-Kubernetes-Security-Specialist" width="200"/>
      - layout: right
        title: "AWS Certified Solutions Architect – Associate"
        link: https://www.credly.com/badges/281f50c8-60a8-4fc2-8d6d-e9bb46ff9900
        link_text: credly link
        caption: March 28, 2023 – March 28, 2026
        description: |
          <img src="images/AWS-Certified-Solutions-Architect-Associate.png" alt="AWS-Certified-Solutions-Architect-Associate" width="200"/>
      - layout: right
        title: "HashiCorp Certified: Terraform Associate (003)"
        link: https://www.credly.com/badges/27a48941-bae6-45ba-a3ed-f225a8774ae7
        link_text: credly link
        caption: February 11, 2024 – February 11, 2026
        description: |
          <img src="images/Terraform-Associate.png" alt="Terraform-Associate" width="200"/>
      - layout: right
        title: "HashiCorp Certified: Vault Associate (002)"
        link: https://www.credly.com/badges/447a57f3-483f-4fe6-a107-9ff196cbd873
        link_text: credly link
        caption:  July 13, 2023 – July 13, 2025
        description: |
          <img src="images/Vault-Associate.png" alt="Vault-Associate" width="200"/>

  - title: Hobby
    layout: text
    content: |
      - **Gardening:** spend my free time in the garden when I need to switch off and relax for a moment
      - **Playing the guitar:** not a pro, but can strum the strings
      - **Cocktail shaking:** "Mai Tai" is one of my favorites

# Footer
footer_show_references: true
references_title: <a href="https://www.sejda.com/html-to-pdf?save-link=https%3A%2F%2Fanatolek.github.io%2F&pageSize=a4&pageOrientation=portrait">Save as PDF</a>

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
